@host = http://localhost:3000

###
POST {{host}}/api/auth
Content-Type: application/json

{
    "email": "admin@dasw.mx",
    "password": "admin"
}

###
POST {{host}}/api/users
Content-Type: application/json
x-auth: 

{
    "name": "Luis",
    "lastname": "Fernando",
    "email": "luis.fernando@iteso.mx",
    "password": "123456",
    "usertype": 2
}

###
POST {{host}}/api/groups
Content-Type: application/json
x-auth: 

{
    "title": "Programación Estructurada",
    "code": "P2023_ESI1234F",
    "information": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis, ut impedit rem quisquam accusantium nam repellendus expedita nulla vitae ullam dolor praesentium, excepturi totam. Et laudantium laboriosam mollitia aut accusantium? Aliquid officia quam cupiditate. Natus nemo sunt voluptatibus quas doloremque facere hic eius quisquam voluptas quae porro quia nulla fugiat harum, sapiente laudantium quidem quibusdam! Doloremque provident eos enim modi.",
    "teacher": ""
}

###
POST {{host}}/api/auth
Content-Type: application/json

{
    "email": "luis.fernando@iteso.mx",
    "password": "Luisfer1"
}

###
GET {{host}}/api/groups
x-auth: 

###
GET {{host}}/api/groups/:groupId
x-auth: 

###
GET {{host}}/api/groups/:groupId/studentsToAdd
x-auth: 

###
POST {{host}}/api/groups/:groupId/student/:studentId
x-auth: 

//LOGIN CON PROFESOR
###
POST {{host}}/api/auth
Content-Type: application/json

{
    "email": "pedrogonzales@iteso.mx",
    "password": "Pedro1"
}
###
// Crear una rúbrica
POST  {{host}}/api/rubricas/
x-auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1aXMuZmVybmFuZG9AaXRlc28ubXgiLCJ1aWQiOiJ2NVZnRzRYeHFFWUE1Z0VVWXNKTnMiLCJ1c2VydHlwZSI6MiwiaWF0IjoxNjgzNTUxNzcyfQ.NQQFvXTJOsQ05e9RGd0BlehmNTpL7mc3-Vj-ly5DAAw
Content-Type: application/json

{
    "nombre": "Tarea 1 Web Rubrica",
    "preguntas": ["Mantuvo el HTML y CSS separados en sus archivos?",
    "El companero usa bootstrap para estilizar su pagina web?"],
    "curso":"Desarrollo de Aplicaciones y Servicios Web"
}

//mostrar rubricas de usuario 
###
GET {{host}}/api/rubricas/
x-auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1aXMuZmVybmFuZG9AaXRlc28ubXgiLCJ1aWQiOiJ2NVZnRzRYeHFFWUE1Z0VVWXNKTnMiLCJ1c2VydHlwZSI6MiwiaWF0IjoxNjgzNjg1MDA2fQ.MMdCW9vnYWPdGEw4QTapKfOgHRFi5tEyloP4oIjCrEM

//borrar una rubrica 
###
DELETE {{host}}/api/rubricas/9O4YA6_6t8r3kAl2CPvWY
x-auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlZHJvZ29uemFsZXNAaXRlc28ubXgiLCJ1aWQiOiJuSnliaEh0bmMxck9VTWM5djVBUy0iLCJ1c2VydHlwZSI6MiwiaWF0IjoxNjgzNDMxMjkzfQ.v-jTVZ7ezkdDrwCTwSmdhEUZmhj7aiGrcluAqZ0slaU

//ver una rubrica en especifico:
###
GET {{host}}/api/rubricas/B9QkHQ5EHVa1o46g5ExQs
x-auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlZHJvZ29uemFsZXNAaXRlc28ubXgiLCJ1aWQiOiJuSnliaEh0bmMxck9VTWM5djVBUy0iLCJ1c2VydHlwZSI6MiwiaWF0IjoxNjgzNDMzNzc5fQ.hsDBm0ruzKc2nI2IsSm1YUKETCihVdXT5MZezM2XXPA

// Crear una tarea
###
PUT {{host}}/api/rubricas/1KLNxFPt6KR_TVN3kQeSY
x-auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1aXMuZmVybmFuZG9AaXRlc28ubXgiLCJ1aWQiOiJ2NVZnRzRYeHFFWUE1Z0VVWXNKTnMiLCJ1c2VydHlwZSI6MiwiaWF0IjoxNjgzNjg1MDA2fQ.MMdCW9vnYWPdGEw4QTapKfOgHRFi5tEyloP4oIjCrEM
Content-Type: application/json

{
    "nombre":"Evaluacion final del proyecto",
    "preguntas":["El proyecto utiliza structs"],
    "curso": "Programación Estructurada"
}
// Iniciar sesión como estudiante

// Ver las tareas

// Ver una tarea

// Entregar la tarea 

// Iniciar sesión como otro estudiante

// Evaluar la tarea de su compañero

// (Como el profesor) Ver la entrega de la tarea

// (Como el profesor) Asignar una calificación