@host = http://localhost:3000

###
POST {{host}}/api/auth
Content-Type: application/json

{
    "email": "admin@dasw.mx",
    "password": "admin"
}

###
POST {{host}}/api/users
Content-Type: application/json
x-auth: 

{
    "name": "Luis",
    "lastname": "Fernando",
    "email": "luis.fernando@iteso.mx",
    "password": "123456",
    "usertype": 2
}

###
POST {{host}}/api/groups
Content-Type: application/json
x-auth: 

{
    "title": "Programación Estructurada",
    "code": "P2023_ESI1234F",
    "information": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis, ut impedit rem quisquam accusantium nam repellendus expedita nulla vitae ullam dolor praesentium, excepturi totam. Et laudantium laboriosam mollitia aut accusantium? Aliquid officia quam cupiditate. Natus nemo sunt voluptatibus quas doloremque facere hic eius quisquam voluptas quae porro quia nulla fugiat harum, sapiente laudantium quidem quibusdam! Doloremque provident eos enim modi.",
    "teacher": ""
}

###
POST {{host}}/api/auth
Content-Type: application/json

{
    "email": "pedrogonzales@iteso.mx",
    "password": "Pedro1"
}

###
GET {{host}}/api/groups
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGM1OTRhNTNmMmQ2M2E0MzA5MDIyZSIsImVtYWlsIjoibWF1cmljaW8ubm9yaWVnYUBpdGVzby5teCIsInVpZCI6IndrOHNTbU9Wa0s0c0FOa0Z0elVvdiIsInVzZXJ0eXBlIjoxLCJpYXQiOjE2ODM0Mjk3MDB9.FAYtM5Oa-U8y3yWlccYuveXb4BEDPuJQQcBE6pqHMXc

###
GET {{host}}/api/groups/:groupId
x-auth: 

###
GET {{host}}/api/groups/:groupId/studentsToAdd
x-auth: 

###
POST {{host}}/api/groups/:groupId/student/:studentId
x-auth: 

// Ver rúbricas

// Crear una rúbrica

// Crear una tarea

###
POST {{host}}/api/assignments
Content-Type: application/json
x-auth: 

{
  "title": "Primera entrega de requerimientos",
  "description": "Something",
  "dueDate": "2023-06-16T04:59:00.000Z",
  "rubricId": "" 
}

// Iniciar sesión como estudiante
###
POST {{host}}/api/auth
Content-Type: application/json

{
    "email": "mauricio.noriega@iteso.mx",
    "password": "123456"
}


// Ver una tarea
###
GET {{host}}/api/assignments/:id
x-auth: 

// Entregar la tarea 
POST {{host}}/api/assignments/submit/:assignmentId
x-auth:

// Iniciar sesión como otro estudiante

// Evaluar la tarea de su compañero

// (Como el profesor) Ver la entrega de la tarea

// (Como el profesor) Asignar una calificación